FROM --platform=linux/amd64 amazoncorretto:17-alpine
VOLUME /tmp 
COPY target/Project1_User_Service-0.0.1-SNAPSHOT.jar user-ms.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/user-ms.jar"]